# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BookStore' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BookStore
  pod 'Firebase/Core', '~> 5.15.0'

  target 'BookStore-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  end

  target 'BookStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BookStore-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BookStore-tvOS

  # target 'BookStore-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
